meta_product_name: "Band"
meta_title: "Band - Find your (soul)(pop)(indie) mate!"
meta_description: "The new favourite app of every musician who's looking to meet new people to play music with."
meta_image: "cover.png"
